input {
  file {
    path => "/data/*.pdf"
    mode => "read"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  pdf {
    source => "path"
    target => "attachment"
  }

  mutate {
    rename => { "path" => "file_path" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "pdf_index"
  }

  stdout { codec => rubydebug }
}